/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ModelValidationRouteImport } from './routes/model-validation'
import { Route as ModelTransformRouteImport } from './routes/model-transform'
import { Route as ModelGenerationRouteImport } from './routes/model-generation'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const ModelValidationRoute = ModelValidationRouteImport.update({
  id: '/model-validation',
  path: '/model-validation',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelTransformRoute = ModelTransformRouteImport.update({
  id: '/model-transform',
  path: '/model-transform',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelGenerationRoute = ModelGenerationRouteImport.update({
  id: '/model-generation',
  path: '/model-generation',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/model-generation': typeof ModelGenerationRoute
  '/model-transform': typeof ModelTransformRoute
  '/model-validation': typeof ModelValidationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/model-generation': typeof ModelGenerationRoute
  '/model-transform': typeof ModelTransformRoute
  '/model-validation': typeof ModelValidationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/model-generation': typeof ModelGenerationRoute
  '/model-transform': typeof ModelTransformRoute
  '/model-validation': typeof ModelValidationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/model-generation'
    | '/model-transform'
    | '/model-validation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/model-generation'
    | '/model-transform'
    | '/model-validation'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/model-generation'
    | '/model-transform'
    | '/model-validation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ModelGenerationRoute: typeof ModelGenerationRoute
  ModelTransformRoute: typeof ModelTransformRoute
  ModelValidationRoute: typeof ModelValidationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/model-validation': {
      id: '/model-validation'
      path: '/model-validation'
      fullPath: '/model-validation'
      preLoaderRoute: typeof ModelValidationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model-transform': {
      id: '/model-transform'
      path: '/model-transform'
      fullPath: '/model-transform'
      preLoaderRoute: typeof ModelTransformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model-generation': {
      id: '/model-generation'
      path: '/model-generation'
      fullPath: '/model-generation'
      preLoaderRoute: typeof ModelGenerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ModelGenerationRoute: ModelGenerationRoute,
  ModelTransformRoute: ModelTransformRoute,
  ModelValidationRoute: ModelValidationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
